# NumPy 

Nessa aula vamos aprender um pouco sobre como trabalhar com a biblioteca Numpy. É um pacote para a linguagem Python que suporta arrays e matrizes multidimensionais, possuindo uma larga coleção de funções matemáticas para trabalhar com estas estruturas.

### Load NumPy and check version

In [1]:
# Como o NumPy não é nativo do Python nós precisamos fazer uma importação da biblioteca 
import numpy as np


#vamos verificar a versão instalada
np.__version__

'1.18.5'

#### Numpy é uma biblioteca enorme que trabalha com computação científica (tanto que é conhecida o container dos containers dos array) 

In [2]:
x = np.arange(10)
print(x)
type(x)

[0 1 2 3 4 5 6 7 8 9]


numpy.ndarray

### Vamos começar a fazendo um execício sobre lista.
Será criada uma lista de 0 à 1000000, crie uma segunda lista na qual os elementos sejam o quadrado de cada elemento da primeira lista

In [3]:
z = list(range(1000000))
## vamos embora!
z2=[]
for i in range (0, len(z)):
    z2.append(z[i]**2)
z2[0:10]

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

### Agora vamos ver como é a performance do array comparada com a lista

In [4]:
y = np.arange(1000000)
z = y ** 2
z[0:10]

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

### Transformando uma array em lista

In [5]:
y1 = list(z)

### Transformando uma lista em array

In [6]:
z3 = np.array(z2)

### Em uma lista podemos adicionar vários tipos diferentes de variáveis 

In [7]:
animal = ['Dog', 'Mammal', 45, 7]
print(animal)

['Dog', 'Mammal', 45, 7]


### No array isso não acontece, todas as variáveis serão do mesmo tipo

In [8]:
 
np.array(animal)

array(['Dog', 'Mammal', '45', '7'], dtype='<U6')

### Array pode ser ter quanta dimensões desejarmos, porém o mais comum é termos arrays de 1, 2 e 3 dimensões

In [9]:
#Como será que fica um array de 3 dimensões?
ndim = np.arange(27).reshape(3,3,3)
#print(ndim)

In [10]:
#um array de quatro dimensões
twos = np.arange(16).reshape(2,2,2,2)
#print(twos)

### Quando desejamos utilizar um array para salvar dados, devemos fazer uma declaração de variável inicialmente para "guardar" memória para salvar futuros dados

In [11]:
## Há algumas maneiras de se fazer isso
print(np.ones((3,5)), end='\n\n')
print(np.zeros((3,5)), end='\n\n')
print(np.eye(3,5))

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]


### Como acessar dados dentro do array

In [12]:
## vamos criar um array de maneira randômica de tamanho 15
data = np.random.randint(10, size=15)
print(data)

[0 1 2 5 0 1 4 0 8 5 6 2 0 5 5]


In [13]:
data[4:8]

array([0, 1, 4, 0])

In [14]:
data = data.reshape(3,5)
data

array([[0, 1, 2, 5, 0],
       [1, 4, 0, 8, 5],
       [6, 2, 0, 5, 5]])

In [15]:
data[0,0]

0

### Vamos fazer mais um exercício?

Coloque a lista seguinte e em ordem crescente:
1. lista_exercico = [8, 5, 2, 4, 9]

### Argsort --> uma função do numpy que irá retornar a sequência de indices que nos dará uma sequência crescente ou decrescente

In [16]:
x = np.array([8, 5, 2, 4, 9])
print(np.argsort(x))
print(x[x.argsort()])
print(x)

[2 3 1 0 4]
[2 4 5 8 9]
[8 5 2 4 9]


In [17]:
##podemos usar o sequenciamento de indices de um array e um outro

grade = np.array([3, 5, 1, 6, 2, 7])
ages = np.array([8, 10, 6, 11, 7, 12])

In [18]:
sort_index = np.argsort(ages)

In [19]:
print(grade[sort_index])
print(ages[sort_index])

[1 2 3 5 6 7]
[ 6  7  8 10 11 12]


In [20]:
## orde decrescente 
print(list(ages[sort_index])[::-1])

[12, 11, 10, 8, 7, 6]


### Vamos manipular algum array

In [21]:
import numpy.random as npr
x = npr.randint(-10,10, size=100)
print(x)

[ -9  -3   5   2  -9  -3   4   0  -5   3   5  -5   5  -1   3   7  -1   3
   2  -4   8   7  -6  -9   3   3  -7  -7   6  -7  -6   4   9   8  -3  -4
  -3   4   9  -8  -2   3   1   5  -1   0  -7   3   6  -9   6  -6   9  -4
   6   5   5 -10  -7   5 -10   2 -10   2   7   8   6  -7   2  -5  -4  -8
   8   8  -1   8  -1  -9   0   6 -10  -7 -10   8   9   5   8   2   3  -4
   5   9  -8   7  -8   3  -5  -1   9   5]


### Mais um exercício 
1. No array acima, substitua os valores menores que -1 por -1, e valores maiores que 5 por 5. Fazendo uso de for 

In [22]:
##Quer uma maneira fácil de se fazer isso?
print(x.clip(-1, 5))

[-1 -1  5  2 -1 -1  4  0 -1  3  5 -1  5 -1  3  5 -1  3  2 -1  5  5 -1 -1
  3  3 -1 -1  5 -1 -1  4  5  5 -1 -1 -1  4  5 -1 -1  3  1  5 -1  0 -1  3
  5 -1  5 -1  5 -1  5  5  5 -1 -1  5 -1  2 -1  2  5  5  5 -1  2 -1 -1 -1
  5  5 -1  5 -1 -1  0  5 -1 -1 -1  5  5  5  5  2  3 -1  5  5 -1  5 -1  3
 -1 -1  5  5]


### Como fazer uma escolha aleatória?

In [23]:
y = npr.choice(x, 10, replace=False)
y

array([  9,   5,  -7,   3, -10,  -5,   6,  -5,   8,   8])

### que tal uma escolha baseada em probabilidades?

In [24]:
npr.choice(y, 1, p=[.05, .1, .15, .15, .05, .1, 0.15, .07, .08, 0.1])

array([6])

### Para não perder o costume um exercício
1. Encontre os elementos unicos do array a seguir
2. O retorno deve ser o elemento e seu index
3. A quantidade observada em cada elemento

In [25]:
symbols = np.array(['BCD', 'ACD', 'ACD', 'ACD', 'ABD', 'ABC', 'ABC', 'ABD', 'ABD',
       'BCD', 'BCD', 'ABC', 'ABC', 'BCD', 'ACD'])

In [26]:
a, b, c = np.unique(symbols, return_index=True, return_counts=True)

In [27]:
a

array(['ABC', 'ABD', 'ACD', 'BCD'], dtype='<U3')

In [28]:
c

array([4, 3, 4, 4])

In [29]:
a.shape

(4,)

In [30]:
b

array([5, 4, 1, 0])

### Como combinar arrays? 

In [31]:
array_1 = [[1,2],[3,4]]
array_2 = [[5,6],[7,8]]

In [32]:
np.concatenate((array_1, array_2))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [33]:
np.concatenate((array_1,array_2), axis=1)

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

### Flatten Array

In [34]:
arr = np.arange(27).reshape(3,3,3)
arr

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [35]:
arr.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

### Comando Where

In [36]:
x = npr.randint(-10,10, size=100)
x

array([ -1,  -3,   5,  -4,  -9,  -3, -10,   8,   3,  -6,   5,   9,  -3,
         4,  -1, -10,   2,   9,  -6,   1,  -7,   2, -10,   1,   4,  -7,
        -7,  -7,   9,   1,   7,  -5,  -9,  -5,   9,  -2,   3,  -4,  -8,
        -5, -10,   9,   4,  -2,  -4,  -9,   0,   5,   1,  -2,  -3,  -2,
         9,  -3,   6,   0,  -2,  -2,   2,  -3,  -6,   6,   4,  -3,  -2,
         6,  -8,   4,   5,   6,  -4,  -7,  -6,   3,   2,   4,   5,   4,
        -2,   6,  -3,   2,   6,  -2,  -4,  -8,   6,   7,  -7,   8, -10,
        -1,  -2,  -6,  -2,   3,   8,  -9,   9,   1])

In [37]:
positive = np.where(x > 0, 200, x)
positive

array([ -1,  -3, 200,  -4,  -9,  -3, -10, 200, 200,  -6, 200, 200,  -3,
       200,  -1, -10, 200, 200,  -6, 200,  -7, 200, -10, 200, 200,  -7,
        -7,  -7, 200, 200, 200,  -5,  -9,  -5, 200,  -2, 200,  -4,  -8,
        -5, -10, 200, 200,  -2,  -4,  -9,   0, 200, 200,  -2,  -3,  -2,
       200,  -3, 200,   0,  -2,  -2, 200,  -3,  -6, 200, 200,  -3,  -2,
       200,  -8, 200, 200, 200,  -4,  -7,  -6, 200, 200, 200, 200, 200,
        -2, 200,  -3, 200, 200,  -2,  -4,  -8, 200, 200,  -7, 200, -10,
        -1,  -2,  -6,  -2, 200, 200,  -9, 200, 200])