# NumPy 

Nessa aula vamos aprender um pouco sobre como trabalhar com a biblioteca Numpy. É um pacote para a linguagem Python que suporta arrays e matrizes multidimensionais, possuindo uma larga coleção de funções matemáticas para trabalhar com estas estruturas.

### Load NumPy and check version

In [6]:
# Como o NumPy não é nativo do Python nós precisamos fazer uma importação da biblioteca 
import numpy as np


#vamos verificar a versão instalada
np.__version__

'1.18.5'



#### Numpy é uma biblioteca enorme que trabalha com computação científica (tanto que é conhecida o container dos containers dos array) 

In [38]:
x = np.arange(10)
print(x)
type(x)

[0 1 2 3 4 5 6 7 8 9]


numpy.ndarray

### Vamos começar a fazendo um execício sobre lista.
Será criada uma lista de 0 à 1000000, crie uma segunda lista na qual os elementos sejam o quadrado de cada elemento da primeira lista

In [32]:
z = list(range(1000000))
y = []
for i in z:
  y.append(i**2)# append adiciona ao quadrado
y[0:5]# VAI LER OS DADOS DO INDICE 0 AO 5

[0, 1, 4, 9, 16]

### Agora vamos ver como é a performance do array comparada com a lista

In [29]:
z = np.arange(10000)
y = z **2
y[0:5]

array([ 0,  1,  4,  9, 16])

In [36]:
y[0:10]

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

### Em uma lista podemos adicionar vários tipos diferentes de variáveis 

In [ ]:
animal = ['Dog', 'Mammal', 45, 7]
print(animal)

In [ ]:
## No array isso não acontece, todas as variáveis serão do mesmo tipo 
np.array(animal)

### Array pode ser ter quanta dimensões desejarmos, porém o mais comum é termos arrays de 1, 2 e 3 dimensões

In [40]:
#Como será que fica um array de 3 dimensões?
ndim = np.arange(27).reshape(3,3,3)
print(ndim)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [43]:
#um array de quatro dimensões
twos = np.arange(16).reshape(2,2,2,2)
print(twos)

[[[[ 0  1]
   [ 2  3]]

  [[ 4  5]
   [ 6  7]]]


 [[[ 8  9]
   [10 11]]

  [[12 13]
   [14 15]]]]


### Quando desejamos utilizar um array para salvar dados, devemos fazer uma declaração de variável inicialmente para "guardar" memória para salvar futuros dados

In [44]:
## Há algumas maneiras de se fazer isso
print(np.ones((3,5)), end='\n\n')
print(np.zeros((3,5)), end='\n\n')
print(np.eye(3,5))

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]


### Como acessar dados dentro do array

In [56]:
## vamos criar um array de maneira randômica de tamanho 15
data = np.random.randint(30, size=15)
print(data)

[26 17 29 25  1 23  9 28 28  4 11 23 27 17 28]


In [57]:
data[4:8]

array([ 1, 23,  9, 28])

In [58]:
data = data.reshape(3,5)
data

array([[26, 17, 29, 25,  1],
       [23,  9, 28, 28,  4],
       [11, 23, 27, 17, 28]])

In [59]:
data[0,0] 


26

### Vamos fazer mais um exercício?

Coloque a lista seguinte e em ordem crescente:
1. lista_exercico = [8, 5, 2, 4, 9]

In [68]:
 beta = np.array = [8, 5, 2, 4, 9] # TRANSFORMANDO EM UMA ARRAY


In [64]:
beta.sort()

In [65]:
beta

[2, 4, 5, 8, 9]

### Argsort --> uma função do numpy que irá retornar a sequência de indices que nos dará uma sequência crescente ou decrescente

In [4]:
beta = np.array ([8, 5, 2, 4, 9])

print('Lista original: ', beta, end='\n\n')
print('Lista de index: ', np.argsort(beta), end='\n\n')
print('lista ordenada: ', beta[beta.argsort()])


Lista original:  [8 5 2 4 9]

Lista de index:  [2 3 1 0 4]

lista ordenada:  [2 4 5 8 9]


In [ ]:
##podemos usar o sequenciamento de indices de um array e um outro

grade = np.array([3, 5, 1, 6, 2, 7])
ages = np.array([8, 10, 6, 11, 7, 12])

In [ ]:
sort_index = np.argsort(ages)

In [ ]:
print(grade[sort_index])
print(ages[sort_index])

In [ ]:
## orde decrescente 
print(list(ages[sort_index])[::-1])

### Vamos manipular algum array

In [14]:
import numpy.random as npr
#para fixar os numeros aleatorios npr.seed
npr.seed(100)
x = npr.randint(-10,10, size=100)
print(x)

[ -2  -7  -3   5   6   0  -8  -8  -8   4  -8   7   6   5  -6   1   6  -1
  -8   2  -6  -9   3   9  -6  -6  -7  -3   7   5  -9   4  -3   6  -8  -1
   9  -8   4   7   6   5  -3   3  -4   2   8 -10  -8   0   7  -2   3   0
   7  -6   8  -2   9   4 -10   3   2   0  -7  -4  -7   5   0   5  -7  -1
   6   1  -6  -5  -3  -4  -8   0   8   3   2  -9  -4   0 -10  -8   9  -6
   8  -6  -7  -1   6   6  -4  -5  -4  -3]


### Mais um exercício 
1. No array acima, substitua os valores menores que -1 por -1, e valores maiores que 5 por 5. Fazendo uso de for 

In [15]:
y = []
for substituicao in x:
    if substituicao < -1:
        substituicao = -1
        y.append(substituicao)
    elif substituicao > 5:
        substituicao = 5
        y.append(substituicao)
    else:
        substituicao = substituicao
        y.append(substituicao)
y = np.array(y)
y

array([-1, -1, -1,  5,  5,  0, -1, -1, -1,  4, -1,  5,  5,  5, -1,  1,  5,
       -1, -1,  2, -1, -1,  3,  5, -1, -1, -1, -1,  5,  5, -1,  4, -1,  5,
       -1, -1,  5, -1,  4,  5,  5,  5, -1,  3, -1,  2,  5, -1, -1,  0,  5,
       -1,  3,  0,  5, -1,  5, -1,  5,  4, -1,  3,  2,  0, -1, -1, -1,  5,
        0,  5, -1, -1,  5,  1, -1, -1, -1, -1, -1,  0,  5,  3,  2, -1, -1,
        0, -1, -1,  5, -1,  5, -1, -1, -1,  5,  5, -1, -1, -1, -1])

In [16]:
# Maneira mais facil de se fazer a mudanca dos valores
x.clip(-1, 5)

array([-1, -1, -1,  5,  5,  0, -1, -1, -1,  4, -1,  5,  5,  5, -1,  1,  5,
       -1, -1,  2, -1, -1,  3,  5, -1, -1, -1, -1,  5,  5, -1,  4, -1,  5,
       -1, -1,  5, -1,  4,  5,  5,  5, -1,  3, -1,  2,  5, -1, -1,  0,  5,
       -1,  3,  0,  5, -1,  5, -1,  5,  4, -1,  3,  2,  0, -1, -1, -1,  5,
        0,  5, -1, -1,  5,  1, -1, -1, -1, -1, -1,  0,  5,  3,  2, -1, -1,
        0, -1, -1,  5, -1,  5, -1, -1, -1,  5,  5, -1, -1, -1, -1])

### Como fazer uma escolha aleatória?

In [21]:
#replace True - Permite a escolha do mesmo elemento multiplas vezes
#replace false - Nao permite

y = npr.choice(x, 10, replace=True)

y

array([ 7, -8, -8,  8, -1, -3,  9,  6, -2, -2])

### que tal uma escolha baseada em probabilidades?

In [20]:
npr.choice(y, 1, p=[.05, .1, .15, .15, .05, .1, 0.15, .07, .08, 0.1])

array([-6])

### Para não perder o costume um exercício
1. Encontre os elementos unicos do array a seguir
2. O retorno deve ser o elemento e seu index
3. A quantidade observada em cada elemento

In [23]:
symbols = np.array(['BCD', 'ACD', 'ACD', 'ACD', 'ABD', 'ABC', 'ABC', 'ABD', 'ABD',
       'BCD', 'BCD', 'ABC', 'ABC', 'BCD', 'ACD'])

In [31]:
#1
Unicos = list(set(symbols)) 
Unicos

['BCD', 'ABD', 'ABC', 'ACD']

In [42]:
#2
indice = {}
i= 0
for index in range(0,len(symbols)):
    indice[symbols[index]]=i
    i += 1
    
indice

{'BCD': 13, 'ACD': 14, 'ABD': 8, 'ABC': 12}

In [43]:
a, b, c = np.unique(symbols, return_index=True, return_counts=True)

In [47]:
print(a) # elementos

['ABC' 'ABD' 'ACD' 'BCD']


In [48]:
print(b) # 

[5 4 1 0]


In [49]:
print(c) #index

[4 3 4 4]


In [51]:
a.shape # retorna a forma de uma matriz

(4,)

### Como combinar arrays? 

In [ ]:
array_1 = [[1,2],[3,4]]
array_2 = [[5,6],[7,8]]

In [ ]:
np.concatenate((array_1, array_2))

In [ ]:
np.concatenate((array_1,array_2), axis=1)

### Flatten Array

In [ ]:
arr = np.arange(27).reshape(3,3,3)
arr

In [ ]:
arr.flatten()

### Comando Where

In [52]:

x = npr.randint(-10,10, size=100)
x

array([  4,   8,   0,  -4,  -5,  -3,   9, -10,   3,  -3,   8,   4,   6,
        -5,   6,  -8,   7,   6,   5,  -7,   9,   2,  -5,  -8, -10,   3,
        -1,   3,  -7,   5,   8,   5,   3,   1,   7,  -5,   7,  -3,  -4,
        -5,   9, -10,  -1,   3,  -9,  -6,   9,  -9, -10,  -4,  -7,  -7,
         9,   8,  -1,   4,   8,   4,  -3,   7,   8,  -2,   3,   2,  -7,
        -8,   1,   8,  -7,  -8, -10,  -4,   1,   8,   2,   7,  -9,  -8,
         1,   8,  -4,   2,  -8,  -6,  -5,   7,  -3,  -5,  -6,   6,  -9,
         3,   6,   7, -10,  -7,   8,   0,  -4,  -7])

In [54]:
#primeiro parametro e a condicao deseja
#segundo parametro e a acao caso a condicao seja verdadeira
# terceiro parametro caso a acao seja falsa
positive = np.where((x > -1), 200, x) # para todos elementos maiores que -1, substitua por 200, se nao permance os valores de x
positive

array([200, 200, 200,  -4,  -5,  -3, 200, -10, 200,  -3, 200, 200, 200,
        -5, 200,  -8, 200, 200, 200,  -7, 200, 200,  -5,  -8, -10, 200,
        -1, 200,  -7, 200, 200, 200, 200, 200, 200,  -5, 200,  -3,  -4,
        -5, 200, -10,  -1, 200,  -9,  -6, 200,  -9, -10,  -4,  -7,  -7,
       200, 200,  -1, 200, 200, 200,  -3, 200, 200,  -2, 200, 200,  -7,
        -8, 200, 200,  -7,  -8, -10,  -4, 200, 200, 200, 200,  -9,  -8,
       200, 200,  -4, 200,  -8,  -6,  -5, 200,  -3,  -5,  -6, 200,  -9,
       200, 200, 200, -10,  -7, 200, 200,  -4,  -7])

In [59]:
#pegando elementos de uma array que nao estajam em sequencia
nova_array = np.arange(75).reshape(3,5,5)
nova_array

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24]],

       [[25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49]],

       [[50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64],
        [65, 66, 67, 68, 69],
        [70, 71, 72, 73, 74]]])

In [61]:
nova_array[1,3,3] # pegando o elemento da segunda array - indice 1 - da terceira coluna - indice3

43